openapi: 3.0.0
info:
  version: 1.0.0
  title: Digital Bank API
  license:
    name: TBD
  description: API for Digital Bank Authentication
  contact:
    name: Aleksey Lysak
servers:
  - url: 'http://localhost:8080/auth'
paths:
  /signup/initiate:
    post:
      summary: Initiate Sign Up
      operationId: sign-up-initiate
      tags:
        - signup
      responses:
        '202':
          description: Request Accepted
        '403':
          description: Request Forbidden
        '409':
          description: Request Conflict
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contract'
            examples: {}
        description: Initiate Sign Up Request Payload
      description: Initiate Digital Bank Sign Up
    parameters: []
  /signup/complete:
    post:
      summary: Complete Sign Up
      operationId: sign-up-complete
      tags:
        - signup
      responses:
        '200':
          description: Request Success
        '403':
          description: Request Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupComplete'
            examples: {}
        description: Complete Sign Up Request Payload
      description: Complete Digital Bank Sign Up
    parameters: []
  /password/reset/initiate:
    post:
      summary: Reset Password
      operationId: reset-password-initiate
      tags:
        - password
      responses:
        '202':
          description: Request Accepted
        '403':
          description: Request Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contract'
            examples: {}
        description: Reset Password Request Payload
      description: Reset Passsword
    parameters: []
components:
  schemas:
    Contract:
      description: Client full contract data
      type: object
      title: Contract
      x-examples: {}
      properties:
        phone:
          type: string
          description: Client phone number
        contract:
          type: string
          description: Client contract number
        birthdate:
          type: string
          format: date
          description: Client birthday
      required:
        - phone
        - contract
        - birthdate
    SignupComplete:
      description: ''
      type: object
      title: SignupComplete
      properties:
        phone:
          type: string
          description: Client phone number
        otpCode:
          type: string
          description: OTP Token received in SMS
        pushToken:
          type: string
          description: The FCM push token
        publicKey:
          type: string
          description: Device public key
        password:
          type: string
          description: Client password
      required:
        - phone
        - otpCode
        - password
        - pushToken
        - publicKey
tags:
  - name: signup
  - name: signin
  - name: device
  - name: password
