@startuml
title: SignUp Flow
'skinparam dpi 300
autonumber

actor Client as user
participant Mobile as mob
participant "API Digital" as api
participant "DB Digital" as dbd
participant "SMS Gateway" as sms
participant "Push Gateway" as fcm

user -> mob: Selects: SignUp (menu/button)
user -> mob: Enters: PhoneNumber, Birthday, Contract
mob -> api: POST /auth/signup (PhoneNumber, Birthday, Contract)
api -> dbd: Lookup client record by:\nPhoneNumber + Birthday + Contract
api <-- dbd: Lookup result
alt Client not found
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot SignUp. Contact bank
end
alt Client already activated (status == ACTIVE)
    mob <-- api: HTTP 409 Conflict
    user <-- mob: Popup message: Use Sign In Instead
end
api -> api: Generate OTP Token (Code, Expire Time)
api -> dbd: Save OTP Token (Code, Expire Time) in client record
api <-- dbd: Client record updated
api -> sms: Send SMS (PhoneNumber, OTP Code)
mob  <-- api: HTTP 202 Accepted
user <-- mob: New screen opened
alt Meanwhile executed in background
    mob -> mob: Generates keys: [PublicKey, PrivateKey]
    mob -> mob: Generates PublicKey Fingerprint.\nIt will serve as Device Id
    mob -> fcm: Get push token
    mob <-- fcm: Push Token
end
user -> user: Waits for SMS with OTP Code
mob <-- sms: SMS with OTP Code
user -> mob: Enters OTP Code
user -> mob: Enters Password and Confirms Password
mob -> api: PATCH /auth/signup
note right mob
Payload includes:
- Phone Number
- Push Token
- Public Key
- Device Id (Fingerprint)
- Password
- OTP Code
end note
api -> dbd: Lookup client record by PhoneNumber
api <-- dbd: Lookup result
alt Client not found
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot SignUp. Contact bank
end
alt Client already activated (status == ACTIVE)
    mob <-- api: HTTP 409 Conflict
    user <-- mob: Popup message: Use Sign In Instead
end
api -> api: Gets OTP Token (Code, Expire Time)\nfrom client record
api -> api: Validates OTP Token against\nreceived OTP Code
api -> api: Validates presence of:\nPush Token, Public Key, Device Id
alt OTP Token Validation failed | Device Keys Validation failed
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot SignUp. Contact bank
end
api -> api: Creates credential record (Hashed Password, Salt)
api -> dbd: Saves credential record
api -> api: Creates device record with:\nPush Token, Public Key, Device Id
api -> dbd: Saves device record
api -> api: Activates client record
note over api
Set status=ACTIVE
Set otp token=NULL
Set credential reference
end note
api -> dbd: Saves client record
api -> api: Generates JWT Token
mob <-- api: HTTP 200 (JWT Token)
mob -> mob: Stores Private Key, Push Token, Device Id\nin device storage
user <-- mob: Home screen opened

@enduml
