@startuml

hide circle
skinparam linetype ortho

title "Logic ERD for Digital Backend"

entity "Client" {
  *id: uuid <<PK>>
  --
  *phone_number: text (indexed)
  *birthday: date
  *contract_number: text
  keycloak_user_id: uuid (indexed)
}

entity "MobileDevice" {
  *id: uuid <<PK>>
  --
  *activated_at: datetime
  public_key: text
  push_token: text
}

"Client" ||..o| MobileDevice

@enduml