@startuml
title "ERD for Digital Backend"
hide circle
'skinparam linetype ortho

entity "Client" as client {
    *id: number <<PK>>
    --
    *phone: text
    *birthday: date
    *contract: text
    *status: enum (ACTIVE, INACTIVE)
    credential: number <<FK>>
    otp_code: varchar(6)
    opt_exp_time: datetime
}

entity "Credential" as cred {
    *id: number <<PK>>
    --
    *password: text
    *salt: text
}

entity "Device" as device {
    *id: number <<PK>>
    --
    *is_active: boolean
    *push_token: text
    *public_key: text
}

'Relations
client ||--o{ cred
client ||--o{ device


'entity "Device" as device {
'  *id: uuid <<PK>>
'  --
'  *activated_at: datetime
'  public_key: text
'  push_token: text
'}
'
'cli ||..o| device

@enduml