@startuml
title: New Device Registration Flow

actor Client as user
participant Mobile as Mob
participant "SMS Gateway" as sms
participant "Push Gateway" as push
participant DigitalDB
participant "Keycloak + Extension" as Keycloak

autonumber

activate user
user -> Mob: PhoneNumber, Password
activate Mob
Mob -> Keycloak: POST /auth/deviceRegistration (PhoneNumber, Password)
activate Keycloak

Keycloak -> DigitalDB: findClientRecord(PhoneNumber, Password): ClientRecord
activate DigitalDB
DigitalDB --> Keycloak: ClientRecord
deactivate DigitalDB
alt ClientRecord is NOT found
    Keycloak --> Mob: HTTP 202
end
Keycloak -> Keycloak: saveInOTPContext(ClientRecord.id)
Keycloak -> Keycloak: generateAndSaveOTP(): OTP
Keycloak --> Mob: HTTP 202
deactivate Mob
Keycloak -> sms: sendSMS(phone=PhoneNumber, data=OTP)
deactivate Keycloak
activate sms

sms -> Mob: SMS with OTP
deactivate sms
activate Mob
Mob -> push: getPushToken(): Push Token
activate push
push --> Mob: Push Token
deactivate push
Mob -> Mob: generateKeys(): [PublicKey, PrivateKey]
user -> Mob: Enter OTP
Mob -> Keycloak: POST /auth/deviceRegistration/complete (OTP, Push Token, PublicKey)
activate Keycloak
Keycloak -> Keycloak: validateOTP(OTP)
Keycloak -> DigitalDB: createMobileDevice(ClientId, Push Token, PublicKey)
activate DigitalDB
DigitalDB --> Keycloak:
deactivate DigitalDB
Keycloak -> Keycloak: generateJWT(scope="regular_user"): JWT
Keycloak --> Mob: HTTP 200 {jwt: JWT}
deactivate Keycloak

@enduml
