@startuml
title: Reset Password Flow
autonumber

actor Client as user
participant Mobile as mob
participant "API Digital" as api
participant "DB Digital" as dbd
participant "SMS Gateway" as sms

user -> mob: Selects: Reset Password (menu/button)
user -> mob: Enters: PhoneNumber
mob -> api: POST /auth/password/reset (PhoneNumber)
api -> dbd: Lookup client record by PhoneNumber
api <-- dbd: Lookup result
alt Client Validation failed
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end
api -> api: Generates OTP Token (Code, Expire Time)
api -> dbd: Saves OTP Token (Code, Expire Time) in client record
api <-- dbd: Client record updated
api -> sms: Sends SMS (PhoneNumber, OTP Code)
mob  <-- api: HTTP 202 Accepted
user <-- mob: New screen opened
mob -> mob: Waits for user data
user -> user: Waits for SMS with OTP Code
mob <-- sms: SMS with OTP Code
user -> mob: Enters OTP Code
user -> mob: Enters Password and Confirms Password
mob -> api: PATCH /auth/password/reset \nPhoneNumber, OTP Code, Password
api -> dbd: Lookup client record by PhoneNumber
api <-- dbd: Lookup result
alt Client Validation failed
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end
api -> api: Get OTP Token (Code, Expire Time)\nfrom client record
api -> api: Validates OTP Token against\nreceived OTP Code
alt Token Validation failed
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end
api -> api: Creates credential record (Hashed Password, Salt)
api -> dbd: Saves credential record
api -> api: Updates client record:\n-sets credential reference\n-clears OTP Token
api -> dbd: Saves client record
mob <-- api: HTTP 200 OK
user <-- mob: Home screen opened

@enduml
