@startuml
title: Reset Password Flow
autonumber

actor Client as user
participant Mobile as mob
participant "API Digital" as api
participant "DB Digital" as dbd
participant "SMS Gateway" as sms

user -> mob: Selects: Reset Password (menu/button)
user -> mob: Enters: PhoneNumber, Birthday, Contract
mob -> api: POST /auth/password/reset/initiate (PhoneNumber, Birthday, Contract)
api -> dbd: Lookup client record by:\nPhoneNumber + Birthday + Contract
api <-- dbd: Lookup result
alt Client not found
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end

note over api
Otherwise, the client is
eligible for Reset Password
end note

api -> api: Generate OTP Token (Code, Expire Time)
api -> dbd: Save OTP Token (Code, Expire Time) in client record
api <-- dbd: Client record updated
api -> sms: Send SMS (PhoneNumber, OTP Code)

mob  <-- api: HTTP 202 Accepted
user <-- mob: New screen opened
newpage

mob -> mob: Waits for user data
user -> user: Waits for SMS with OTP Code
mob <-- sms: SMS with OTP Code

user -> mob: Enter OTP Code
user -> mob: Enter Password and Confirm Password

mob -> api: POST /auth/password/reset/complete \nPhoneNumber, OTP Code, Password
api -> dbd: Lookup client record by PhoneNumber
api <-- dbd: Lookup result
alt Client not found
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end
api -> api: Get OTP Token (Code, Expire Time)\nfrom client record
api -> api: Validate OTP Token against\nreceived OTP Code
alt Invalid token
    mob <-- api: HTTP 403 Forbidden
    user <-- mob: Popup message: Cannot Reset Password. Contact bank
end
note over api
Token is valid
end note

api -> api: Create credential record (Hashed Password, Salt)
api -> dbd: Save credential record
api -> api: Update client record
note over api
Set otp token=NULL
Set credential reference
end note
api -> dbd: Save client record

api -> api: Generate JWT Token
mob <-- api: HTTP 200 (JWT Token)
user <-- mob: Home screen opened

@enduml
